import type { Metadata } from "next";
import specJson from "@/public/openapi.json";
import { Fragment, type ReactNode } from "react";
import { SiteHeader, SiteFooter } from "@/components/veraxius";
import { CodeTabs } from "./code-tabs";
import { PERFORMANCE } from "./performance";

export const metadata: Metadata = {
  title: "API Documentation | Veraxius",
  description:
    "The AIM API: ask whether an AI agent is allowed to act before it acts. Quickstart, authentication, idempotency, errors, full endpoint reference and measured performance.",
};

/* ------------------------------------------------------------------ */
/* OpenAPI spec (public/openapi.json, generated by scripts/generate-openapi.mjs) */
/* ------------------------------------------------------------------ */

type Schema = {
  $ref?: string;
  type?: string | string[];
  enum?: string[];
  description?: string;
  required?: string[];
  properties?: Record<string, Schema>;
  items?: Schema;
  example?: unknown;
};
type Media = { schema?: Schema; example?: unknown };
type Operation = {
  tags?: string[];
  summary?: string;
  description?: string;
  operationId?: string;
  security?: Record<string, string[]>[];
  parameters?: { name: string; in: string; required?: boolean; description?: string }[];
  requestBody?: { content?: Record<string, Media> };
  responses?: Record<string, { description?: string; content?: Record<string, Media> }>;
};
type Spec = {
  info: { version: string };
  tags: { name: string; description?: string }[];
  paths: Record<string, Record<string, Operation>>;
  components: { schemas: Record<string, Schema> };
};

const spec = specJson as unknown as Spec;

function resolve(s?: Schema): Schema | undefined {
  if (!s?.$ref) return s;
  return spec.components.schemas[s.$ref.split("/").pop() as string];
}

function typeLabel(s?: Schema): string {
  const r = resolve(s);
  if (!r) return "";
  if (s?.$ref) return s.$ref.split("/").pop() as string;
  if (r.enum) return r.enum.join(" | ");
  const t = Array.isArray(r.type) ? r.type.filter((x) => x !== "null").join(" | ") : r.type ?? "";
  return t === "array" && r.items ? `${typeLabel(r.items)}[]` : t;
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

/** `code` and **bold** inside spec descriptions. */
function rich(text?: string): ReactNode[] {
  if (!text) return [];
  const out: ReactNode[] = [];
  const re = /(`[^`]+`)|(\*\*[^*]+\*\*)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  let i = 0;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push(text.slice(last, m.index));
    if (m[1]) out.push(<Code key={i++}>{m[1].slice(1, -1)}</Code>);
    else out.push(<strong key={i++} style={{ color: "#ffffff" }}>{m[2].slice(2, -2)}</strong>);
    last = m.index + m[0].length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

/* ------------------------------------------------------------------ */
/* Shared styles                                                        */
/* ------------------------------------------------------------------ */

const eyebrow = "font-dm-mono text-[11px] uppercase text-[var(--amber)]";
const h2Style = { fontSize: "clamp(24px, 2.6vw, 32px)", lineHeight: 1.2, color: "#ffffff" } as const;
const bodyStyle = { fontSize: "16px", lineHeight: 1.7, color: "var(--text-secondary)" } as const;
const cardStyle = { borderColor: "rgba(255,255,255,0.1)", backgroundColor: "rgba(255,255,255,0.02)" } as const;

function Code({ children }: { children: ReactNode }) {
  return (
    <code className="rounded px-1.5 py-0.5 font-dm-mono text-[0.88em]" style={{ backgroundColor: "rgba(255,255,255,0.07)", color: "var(--text-primary)" }}>
      {children}
    </code>
  );
}

function Pre({ children }: { children: string }) {
  return (
    <pre
      className="mt-3 overflow-x-auto rounded-xl border p-4 font-dm-mono text-[12.5px]"
      style={{ lineHeight: 1.6, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "rgba(0,0,0,0.35)", color: "var(--text-primary)" }}
    >
      <code>{children}</code>
    </pre>
  );
}

function DocSection({ id, label, title, children }: { id: string; label: string; title: string; children: ReactNode }) {
  return (
    <section id={id} className="scroll-mt-28 pt-16 pb-4">
      <div className="text-center">
        <span className={eyebrow} style={{ letterSpacing: "0.18em" }}>
          {label}
        </span>
        <h2 className="font-syne font-extrabold mt-3" style={h2Style}>
          {title}
        </h2>
      </div>
      {children}
    </section>
  );
}

const METHOD_COLORS: Record<string, string> = { get: "#4DA3FF", post: "#34D6B0", put: "var(--amber)", patch: "var(--amber)", delete: "#FF8A7A" };

function Method({ m }: { m: string }) {
  return (
    <span
      className="inline-flex min-w-[52px] shrink-0 justify-center rounded-md border px-2 py-0.5 font-dm-mono text-[11px] font-semibold uppercase"
      style={{ color: METHOD_COLORS[m] ?? "#fff", borderColor: "currentColor" }}
    >
      {m}
    </span>
  );
}

/* ------------------------------------------------------------------ */
/* Content                                                              */
/* ------------------------------------------------------------------ */

const FLOW_CURL = `export AIM_API="https://<your-pilot-base-url>"
export AIM_KEY="<your-api-key>"

# 1. The AI wants to act: create a decision
curl -s -X POST "$AIM_API/api/decisions" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"proposed_by_entity_id":"ENT_…","decision_type":"refund",
       "proposed_action":"issue_refund","payload":{"amount":180},
       "idempotency_key":"order-8841-refund"}'

# 2. How much is this agent trusted, from its evidence?
curl -s -X POST "$AIM_API/api/trust/evaluate" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"decision_id":"DEC_…"}'

# 3. What is it allowed to do? EXECUTE | CONSTRAIN | CHALLENGE | ESCALATE | BLOCK
curl -s -X POST "$AIM_API/api/authority/evaluate" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"decision_id":"DEC_…","trust_state_id":"TRS_…","policy_id":"POL_…"}'

# 4. Act only through AIM, with the authority it issued
curl -s -X POST "$AIM_API/api/actions" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"decision_id":"DEC_…","authority_id":"AUT_…","action_type":"issue_refund",
       "payload":{"amount":180},"idempotency_key":"order-8841-refund-act"}'

# 5. Report what happened; it feeds the agent's trust
curl -s -X POST "$AIM_API/api/outcomes" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"action_id":"ACT_…","outcome_type":"refund_settled","success":true}'`;

const FLOW_JS = `const AIM_API = process.env.AIM_API;
const headers = {
  Authorization: \`Bearer \${process.env.AIM_KEY}\`,
  "Content-Type": "application/json",
};
const aim = async (path, body) => {
  const res = await fetch(AIM_API + path, { method: "POST", headers, body: JSON.stringify(body) });
  const data = await res.json();
  if (!res.ok) throw Object.assign(new Error(data.error ?? res.statusText), { status: res.status, data });
  return data;
};

export async function governedRefund({ agentId, policyId, orderId, amount }) {
  const decision = await aim("/api/decisions", {
    proposed_by_entity_id: agentId,
    decision_type: "refund",
    proposed_action: "issue_refund",
    payload: { amount },
    idempotency_key: \`\${orderId}-refund\`,
  });
  const trust = await aim("/api/trust/evaluate", { decision_id: decision.decision_id });
  const auth = await aim("/api/authority/evaluate", {
    decision_id: decision.decision_id,
    trust_state_id: trust.trust_state_id,
    policy_id: policyId,
  });

  if (auth.authority !== "EXECUTE" && auth.authority !== "CONSTRAIN") {
    return { acted: false, authority: auth.authority, next: auth.required_next_step };
  }

  const action = await aim("/api/actions", {
    decision_id: decision.decision_id,
    authority_id: auth.authority_id,
    action_type: "issue_refund",
    payload: { amount },
    idempotency_key: \`\${orderId}-refund-act\`,
  });
  // …perform the refund in your system, then:
  await aim("/api/outcomes", { action_id: action.action_id, outcome_type: "refund_settled", success: true });
  return { acted: true, authority: auth.authority };
}`;

const FLOW_PY = `import os, requests

AIM_API = os.environ["AIM_API"]
HEADERS = {"Authorization": f"Bearer {os.environ['AIM_KEY']}"}

def aim(path, body):
    r = requests.post(AIM_API + path, json=body, headers=HEADERS, timeout=10)
    r.raise_for_status()
    return r.json()

def governed_refund(agent_id, policy_id, order_id, amount):
    decision = aim("/api/decisions", {
        "proposed_by_entity_id": agent_id,
        "decision_type": "refund",
        "proposed_action": "issue_refund",
        "payload": {"amount": amount},
        "idempotency_key": f"{order_id}-refund",
    })
    trust = aim("/api/trust/evaluate", {"decision_id": decision["decision_id"]})
    auth = aim("/api/authority/evaluate", {
        "decision_id": decision["decision_id"],
        "trust_state_id": trust["trust_state_id"],
        "policy_id": policy_id,
    })

    if auth["authority"] not in ("EXECUTE", "CONSTRAIN"):
        return {"acted": False, "authority": auth["authority"]}

    action = aim("/api/actions", {
        "decision_id": decision["decision_id"],
        "authority_id": auth["authority_id"],
        "action_type": "issue_refund",
        "payload": {"amount": amount},
        "idempotency_key": f"{order_id}-refund-act",
    })
    # ...perform the refund in your system, then:
    aim("/api/outcomes", {"action_id": action["action_id"], "outcome_type": "refund_settled", "success": True})
    return {"acted": True, "authority": auth["authority"]}`;

const SETUP_CURL = `# Register the AI agent AIM will govern
curl -s -X POST "$AIM_API/api/entities" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"entity_type":"ai_agent","name":"Billing Refund Agent"}'

# Publish a versioned policy (rules are evaluated top to bottom)
curl -s -X POST "$AIM_API/api/policies" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"policy_key":"refunds","decision_type":"refund","version":"1.0","rules":[
        {"condition":{"trust_score":{"lt":40}},"authority":"BLOCK"},
        {"condition":{"amount":{"gt":1000}},"authority":"ESCALATE"},
        {"condition":{"trust_score":{"gte":60}},"authority":"EXECUTE",
         "envelope":{"amount":{"lte":1000}}},
        {"condition":{"trust_score":{"gte":0}},"authority":"CONSTRAIN"}]}'

# Tell AIM how the agent actually behaves (trust is computed from signals)
curl -s -X POST "$AIM_API/api/signals" \\
  -H "Authorization: Bearer $AIM_KEY" -H "Content-Type: application/json" \\
  -d '{"dimension":"reliability","direction":"positive","strength":0.9,
       "confidence":0.9,"target_entity_id":"ENT_…"}'`;

const STATES = [
  { s: "EXECUTE", d: "Allowed. The action can run through AIM within the policy's envelope." },
  { s: "CONSTRAIN", d: "Allowed with limits. The action runs only inside the returned constraints." },
  { s: "CHALLENGE", d: "Not enough evidence yet. Send more signals or evidence, then evaluate again." },
  { s: "ESCALATE", d: "A human decides. One of your operators approves or rejects it; silence never approves." },
  { s: "BLOCK", d: "Denied. The action cannot run." },
];

const ERRORS: [string, string, string][] = [
  ["400", "Invalid payload", "The body failed validation. Fix the request; retrying will not help."],
  ["401", "Invalid tenant API key", "Missing or wrong `Authorization: Bearer` key."],
  ["403", "Action denied", "The authority does not allow this action. `reason` says why (e.g. `AUTHORITY_EXPIRED`, `ENVELOPE_VIOLATION:amount`)."],
  ["404", "Not found", "The id does not exist in your organization."],
  ["409", "Conflict", "State conflict, e.g. `AUTHORITY_ALREADY_CONSUMED` or an escalation already resolved."],
  ["429", "Too many requests", "Rate limit reached. Back off and retry after the `RateLimit-Reset` seconds."],
  ["500", "Internal error", "Safe to retry with the same idempotency key."],
];

/* ------------------------------------------------------------------ */

export default function DocsPage() {
  const ops = Object.entries(spec.paths).flatMap(([p, methods]) =>
    Object.entries(methods).map(([m, op]) => ({ path: p, method: m, op })),
  );
  const byTag = spec.tags.map((t) => ({ tag: t, ops: ops.filter((o) => o.op.tags?.[0] === t.name) })).filter((g) => g.ops.length);

  return (
    <main className="vx-home-surface min-h-screen overflow-x-clip" style={{ color: "var(--text-primary)" }}>
      <SiteHeader />

      <section className="vx-section" style={{ paddingTop: "150px", paddingBottom: "40px", backgroundColor: "var(--bg-primary)" }}>
        <div className="vx-container">
          <div className="mx-auto max-w-[820px] text-center">
            <span className={eyebrow} style={{ letterSpacing: "0.18em" }}>
              Developers · API v{spec.info.version}
            </span>
            <h1
              className="font-syne font-extrabold mt-4"
              style={{ fontSize: "clamp(32px, 4.4vw, 54px)", lineHeight: 1.1, letterSpacing: "-0.02em", color: "#ffffff" }}
            >
              The AIM <span style={{ color: "var(--amber)", textShadow: "0 0 28px rgba(255,184,77,0.25)" }}>API</span>
            </h1>
            <p className="font-dm-sans mx-auto mt-5 max-w-[620px]" style={{ fontSize: "17px", lineHeight: 1.65, color: "var(--text-secondary)" }}>
              One question before your AI acts: is this agent allowed to do this, right now? A REST API that turns evidence
              into trust, and trust into bounded authority, with every step recorded.
            </p>
            <div className="mt-8 flex flex-col items-stretch justify-center gap-3 sm:flex-row sm:items-center">
              <a
                href="/openapi.json"
                download
                className="inline-flex min-h-11 items-center justify-center rounded-full bg-[var(--amber)] px-7 py-4 font-dm-mono font-semibold text-[13px] uppercase text-[var(--text-on-amber)] transition hover:bg-[var(--amber-glow)]"
                style={{ letterSpacing: "0.08em" }}
              >
                Download OpenAPI spec
              </a>
              <a
                href="/pilots"
                className="inline-flex min-h-11 items-center justify-center rounded-full border px-7 py-4 font-dm-mono font-semibold text-[13px] uppercase transition hover:opacity-80"
                style={{ letterSpacing: "0.08em", borderColor: "rgba(255,184,77,0.45)", color: "var(--amber)" }}
              >
                Request API access
              </a>
            </div>
          </div>
        </div>
      </section>

      <div style={{ backgroundColor: "var(--bg-primary)" }}>
      <div className="vx-container">
        <div className="mx-auto max-w-[900px] pb-24">
          <div className="min-w-0">
            <DocSection id="overview" label="Overview" title="How an integration works">
              <p className="font-dm-sans mt-4" style={bodyStyle}>
                Register your AI agents and a versioned policy, and keep AIM informed with signals about how each agent
                actually behaves. Then, for every consequential action, your system asks AIM first:
              </p>
              <ol className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
                {[
                  ["Decision", "The AI proposes an action."],
                  ["Trust", "AIM scores the agent from its evidence."],
                  ["Authority", "Your policy turns trust into one of five states."],
                  ["Action", "Runs only through AIM, within the authority."],
                  ["Outcome", "What happened feeds back into trust."],
                ].map(([t, d], i) => (
                  <li key={t} className="rounded-xl border p-4" style={cardStyle}>
                    <span className="font-dm-mono text-[12px]" style={{ color: "var(--amber)" }}>
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <p className="font-syne font-bold mt-1 text-[16px]" style={{ color: "#ffffff" }}>
                      {t}
                    </p>
                    <p className="font-dm-sans mt-1 text-[14px]" style={{ lineHeight: 1.5, color: "var(--text-secondary)" }}>
                      {d}
                    </p>
                  </li>
                ))}
              </ol>
              <p className="font-dm-sans mt-5" style={bodyStyle}>
                Every step is written to a tamper-evident governance log you can read back per decision.
              </p>
            </DocSection>

            <DocSection id="quickstart" label="Quickstart" title="From zero to a governed action">
              <p className="font-dm-sans mt-4" style={bodyStyle}>
                <strong style={{ color: "#ffffff" }}>1. Set up once:</strong> register the agent, publish a policy, and send
                signals. Your base URL and API key are issued when your pilot starts.
              </p>
              <CodeTabs samples={[{ label: "curl", code: SETUP_CURL }]} />
              <p className="font-dm-sans mt-8" style={bodyStyle}>
                <strong style={{ color: "#ffffff" }}>2. Before every consequential action</strong>, run the governed flow:
              </p>
              <CodeTabs
                samples={[
                  { label: "curl", code: FLOW_CURL },
                  { label: "JavaScript", code: FLOW_JS },
                  { label: "Python", code: FLOW_PY },
                ]}
              />
            </DocSection>

            <DocSection id="authority-states" label="Authority" title="The five authority states">
              <div className="mt-5 space-y-2">
                {STATES.map((x) => (
                  <div key={x.s} className="flex flex-col gap-1 rounded-xl border px-5 py-4 sm:flex-row sm:items-center sm:gap-5" style={cardStyle}>
                    <span className="font-dm-mono shrink-0 text-[13px] font-semibold sm:w-[110px]" style={{ color: "var(--amber)" }}>
                      {x.s}
                    </span>
                    <span className="font-dm-sans text-[15px]" style={{ lineHeight: 1.55, color: "var(--text-secondary)" }}>
                      {x.d}
                    </span>
                  </div>
                ))}
              </div>
              <p className="font-dm-sans mt-5" style={bodyStyle}>
                Each authority can be used for exactly one action. Using it twice returns <Code>409 AUTHORITY_ALREADY_CONSUMED</Code>,
                even under concurrent requests.
              </p>
            </DocSection>

            <DocSection id="concepts" label="Concepts" title="Authentication, IDs and idempotency">
              <h3 className="font-syne font-bold mt-6 text-[18px]" style={{ color: "#ffffff" }}>Authentication</h3>
              <p className="font-dm-sans mt-2" style={bodyStyle}>
                Every request carries your organization&apos;s API key: <Code>Authorization: Bearer &lt;api_key&gt;</Code>.
                Keys are shown once when issued and only their hash is stored. Resolving an escalation also requires a human
                operator token: <Code>X-Operator-Token</Code>, obtained from <Code>POST /api/tenant-operators/login</Code>.
                Each organization only ever sees its own data.
              </p>
              <h3 className="font-syne font-bold mt-8 text-[18px]" style={{ color: "#ffffff" }}>IDs</h3>
              <p className="font-dm-sans mt-2" style={bodyStyle}>
                IDs are prefixed by type so they are never mixed up: <Code>ENT_</Code> entity, <Code>CTX_</Code> context,{" "}
                <Code>POL_</Code> policy, <Code>SIG_</Code> signal, <Code>EVD_</Code> evidence, <Code>DEC_</Code> decision,{" "}
                <Code>TRS_</Code> trust state, <Code>AUT_</Code> authority, <Code>ACT_</Code> action, <Code>OUT_</Code> outcome.
              </p>
              <h3 className="font-syne font-bold mt-8 text-[18px]" style={{ color: "#ffffff" }}>Idempotency</h3>
              <p className="font-dm-sans mt-2" style={bodyStyle}>
                Decisions and actions accept an <Code>idempotency_key</Code>. Retrying with the same key returns the original
                result with <Code>replayed: true</Code> and never executes twice, so network retries are always safe. Use a
                key derived from your own record, such as the order or ticket id.
              </p>
            </DocSection>

            <DocSection id="errors" label="Errors" title="Errors and rate limits">
              <p className="font-dm-sans mt-4" style={bodyStyle}>
                Errors return a JSON body with an <Code>error</Code> field (and <Code>reason</Code> on denied actions).
              </p>
              <div className="mt-5 overflow-x-auto rounded-xl border" style={cardStyle}>
                <table className="w-full min-w-[520px] text-left font-dm-sans text-[14px]">
                  <thead>
                    <tr className="font-dm-mono text-[11px] uppercase" style={{ letterSpacing: "0.1em", color: "var(--amber)" }}>
                      <th className="px-4 py-3">Status</th>
                      <th className="px-4 py-3">Meaning</th>
                      <th className="px-4 py-3">What to do</th>
                    </tr>
                  </thead>
                  <tbody>
                    {ERRORS.map(([code, name, what]) => (
                      <tr key={code} className="border-t" style={{ borderColor: "rgba(255,255,255,0.06)", color: "var(--text-secondary)" }}>
                        <td className="px-4 py-3 font-dm-mono" style={{ color: "#ffffff" }}>{code}</td>
                        <td className="px-4 py-3" style={{ color: "#ffffff" }}>{name}</td>
                        <td className="px-4 py-3">{rich(what)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="font-dm-sans mt-5" style={bodyStyle}>
                <strong style={{ color: "#ffffff" }}>Rate limits:</strong> {PERFORMANCE.rateLimit} Responses include standard{" "}
                <Code>RateLimit-*</Code> headers.
              </p>
            </DocSection>

            <DocSection id="performance" label="Performance" title="Measured latency">
              <p className="font-dm-sans mt-4" style={bodyStyle}>
                {PERFORMANCE.intro}
              </p>
              <div className="mt-5 grid gap-3 sm:grid-cols-3">
                {PERFORMANCE.headline.map((h) => (
                  <div key={h.label} className="rounded-2xl border p-5" style={cardStyle}>
                    <span className="font-dm-mono text-[11px] uppercase" style={{ letterSpacing: "0.14em", color: "var(--amber)" }}>
                      {h.label}
                    </span>
                    <p className="font-syne font-extrabold mt-2 text-[28px]" style={{ color: "#ffffff" }}>
                      {h.value}
                    </p>
                    <p className="font-dm-sans mt-1 text-[13px]" style={{ lineHeight: 1.5, color: "var(--text-tertiary)" }}>
                      {h.note}
                    </p>
                  </div>
                ))}
              </div>
              <div className="mt-5 overflow-x-auto rounded-xl border" style={cardStyle}>
                <table className="w-full min-w-[520px] text-left font-dm-sans text-[14px]">
                  <thead>
                    <tr className="font-dm-mono text-[11px] uppercase" style={{ letterSpacing: "0.1em", color: "var(--amber)" }}>
                      {PERFORMANCE.table.columns.map((c) => (
                        <th key={c} className="px-4 py-3">{c}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {PERFORMANCE.table.rows.map((row) => (
                      <tr key={row[0]} className="border-t" style={{ borderColor: "rgba(255,255,255,0.06)", color: "var(--text-secondary)" }}>
                        {row.map((cell, i) => (
                          <td key={i} className="px-4 py-3" style={i === 0 ? { color: "#ffffff" } : undefined}>
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <ul className="mt-5 space-y-2 pl-5 font-dm-sans text-[14px]" style={{ listStyleType: "disc", lineHeight: 1.6, color: "var(--text-tertiary)" }}>
                {PERFORMANCE.method.map((m) => (
                  <li key={m}>{m}</li>
                ))}
              </ul>
            </DocSection>

            <DocSection id="reference" label="Reference" title="API reference">
              <p className="font-dm-sans mt-4" style={bodyStyle}>
                Generated from the <a href="/openapi.json" className="underline hover:no-underline" style={{ color: "var(--amber)" }}>OpenAPI 3.1 spec</a>,
                which you can also import into Postman, Insomnia or any OpenAPI code generator.
              </p>
              {byTag.map(({ tag, ops: list }) => (
                <div key={tag.name} className="mt-10">
                  <h3 id={slug(tag.name)} className="font-syne font-bold scroll-mt-28 text-[20px]" style={{ color: "#ffffff" }}>
                    {tag.name}
                  </h3>
                  {tag.description && (
                    <p className="font-dm-sans mt-1 text-[15px]" style={{ color: "var(--text-tertiary)" }}>
                      {tag.description}
                    </p>
                  )}
                  <div className="mt-4 space-y-3">
                    {list.map(({ path: p, method, op }) => {
                      const media = op.requestBody?.content?.["application/json"];
                      const body = resolve(media?.schema);
                      const needsOperator = op.security?.some((s) => "OperatorToken" in s);
                      return (
                        <details key={`${method} ${p}`} id={op.operationId} className="group scroll-mt-28 rounded-xl border" style={cardStyle}>
                          <summary className="flex min-h-12 cursor-pointer list-none flex-wrap items-center gap-x-3 gap-y-1 px-4 py-3">
                            <Method m={method} />
                            <span className="min-w-0 break-all font-dm-mono text-[13px]" style={{ color: "#ffffff" }}>{p}</span>
                            <span className="font-dm-sans text-[14px]" style={{ color: "var(--text-tertiary)" }}>{op.summary}</span>
                          </summary>
                          <div className="border-t px-4 pb-5 pt-4" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
                            {op.description && (
                              <p className="font-dm-sans text-[15px]" style={{ lineHeight: 1.65, color: "var(--text-secondary)" }}>
                                {rich(op.description)}
                              </p>
                            )}
                            {needsOperator && (
                              <p className="font-dm-sans mt-3 text-[14px]" style={{ color: "var(--text-secondary)" }}>
                                Requires <Code>X-Operator-Token</Code> in addition to the API key.
                              </p>
                            )}
                            {op.parameters?.length ? (
                              <Fields
                                title="Parameters"
                                rows={op.parameters.map((prm) => ({ name: prm.name, type: prm.in, required: !!prm.required, description: prm.description }))}
                              />
                            ) : null}
                            {body?.properties && (
                              <Fields
                                title="Request body"
                                rows={Object.entries(body.properties).map(([name, s]) => ({
                                  name,
                                  type: typeLabel(s),
                                  required: body.required?.includes(name) ?? false,
                                  description: resolve(s)?.description,
                                }))}
                              />
                            )}
                            {media?.example !== undefined && (
                              <>
                                <p className="font-dm-mono mt-5 text-[11px] uppercase" style={{ letterSpacing: "0.12em", color: "var(--amber)" }}>Example request</p>
                                <Pre>{JSON.stringify(media.example, null, 2)}</Pre>
                              </>
                            )}
                            <p className="font-dm-mono mt-5 text-[11px] uppercase" style={{ letterSpacing: "0.12em", color: "var(--amber)" }}>Responses</p>
                            <ul className="mt-2 space-y-2">
                              {Object.entries(op.responses ?? {}).map(([code, r]) => {
                                const m = r.content?.["application/json"];
                                const example = m?.example ?? resolve(m?.schema)?.example;
                                const ok = code.startsWith("2");
                                return (
                                  <li key={code}>
                                    <div className="flex items-baseline gap-3 font-dm-sans text-[14px]">
                                      <span className="font-dm-mono font-semibold" style={{ color: ok ? "#34D6B0" : "#FF8A7A" }}>{code}</span>
                                      <span style={{ color: "var(--text-secondary)" }}>{rich(r.description)}</span>
                                    </div>
                                    {ok && example !== undefined && <Pre>{JSON.stringify(example, null, 2)}</Pre>}
                                  </li>
                                );
                              })}
                            </ul>
                          </div>
                        </details>
                      );
                    })}
                  </div>
                </div>
              ))}
            </DocSection>
          </div>
        </div>
      </div>
      </div>

      <SiteFooter />
    </main>
  );
}

function Fields({ title, rows }: { title: string; rows: { name: string; type: string; required: boolean; description?: string }[] }) {
  return (
    <>
      <p className="font-dm-mono mt-5 text-[11px] uppercase" style={{ letterSpacing: "0.12em", color: "var(--amber)" }}>{title}</p>
      <div className="mt-2 divide-y rounded-lg border" style={{ borderColor: "rgba(255,255,255,0.08)" }}>
        {rows.map((f) => (
          <div key={f.name} className="flex flex-col gap-1 px-3 py-2 sm:flex-row sm:gap-4" style={{ borderColor: "rgba(255,255,255,0.06)" }}>
            <div className="shrink-0 sm:w-[190px]">
              <span className="break-all font-dm-mono text-[13px]" style={{ color: "#ffffff" }}>{f.name}</span>
              {f.required && <span className="ml-2 font-dm-mono text-[10px] uppercase" style={{ color: "var(--amber)" }}>required</span>}
            </div>
            <div className="min-w-0 font-dm-sans text-[13.5px]" style={{ color: "var(--text-secondary)" }}>
              <span className="break-words font-dm-mono text-[12px]" style={{ color: "var(--text-tertiary)" }}>{f.type}</span>
              {f.description && (
                <Fragment>
                  {" — "}
                  {rich(f.description)}
                </Fragment>
              )}
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
